name: Continuous Deployment

on:
  push:
    branches: production

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      SSH: ${{secrets.SSH_AMSTERDAM}}
      PASS: ${{secrets.SSH_AMSTERDAM_PASS}}
      URL: admin@amsterdam.server.floatplane.dev
      ROOT: /var/www/api.huisartspoelstra.nl
    steps:
      - uses: actions/checkout@v2
      - run: mkdir ~/.ssh
      - run: 'echo "$SSH" > ~/.ssh/$URL'
      - run: 'echo "IdentityFile ~/.ssh/$URL" > ~/.ssh/config'
      - run: ssh-keyscan -H amsterdam.server.floatplane.dev > ~/.ssh/known_hosts
      - run: chmod 0755 ~/.ssh/; chmod 600 ~/.ssh/$URL; chmod 644 ~/.ssh/known_hosts
      - name: Setup SSH passphrase
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo 'echo $PASS' > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          echo "$SSH" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null

      # Check out the latest production branch on the remote.
      - run: ssh $URL "cd $ROOT; git checkout production; git pull"

      # Restart Deno with PM2
      - run: ssh $URL "cd $ROOT; pm2 start"
